/**
 * image-grid-kit — CSS sprite-sheet output.
 *
 * Takes the piece rectangles from planGrid() (or any list of
 * {name, x, y, w, h}) and writes:
 *   - one class per frame, positioned with background-position
 *   - one @keyframes block that steps through the frames
 *   - one animation class
 *
 * The `step-end` timing function is what makes the sheet play frame by frame
 * instead of sliding between frames.
 */

function slug(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "frame";
}

function pad2(n) { return n < 10 ? "0" + n : String(n); }

function pct(i, n) {
  const v = (i / n) * 100;
  return String(Number(v.toFixed(3)));
}

/**
 * @param {object} o
 * @param {Array<{name?:string,x:number,y:number,w:number,h:number}>} o.pieces
 * @param {string} [o.sheetUrl]   url() value, defaults to "spritesheet.png"
 * @param {string} [o.prefix]     class prefix, defaults to "sprite"
 * @param {string} [o.duration]   animation-duration, defaults to "1s"
 * @param {string} [o.timing]     animation-timing-function, defaults to "step-end"
 * @param {string} [o.iterations] animation-iteration-count, defaults to "infinite"
 * @returns {string} CSS text
 */
export function spriteCss(o) {
  const pieces = (o.pieces || []).slice();
  if (!pieces.length) throw new Error("spriteCss: no pieces given");
  const sheetUrl = o.sheetUrl || "spritesheet.png";
  const prefix = slug(o.prefix || "sprite");
  const duration = o.duration || "1s";
  const timing = o.timing || "step-end";
  const iterations = o.iterations || "infinite";
  const n = pieces.length;

  const lines = [];
  lines.push("/* Generated by image-grid-kit */");
  lines.push("." + prefix + " {");
  lines.push("  background-image: url('" + sheetUrl + "');");
  lines.push("  background-repeat: no-repeat;");
  lines.push("  display: inline-block;");
  lines.push("}");
  lines.push("");

  pieces.forEach((p, i) => {
    const nm = p.name ? slug(p.name) : "frame-" + pad2(i + 1);
    lines.push("." + prefix + "." + prefix + "-" + nm + " {");
    lines.push("  width: " + p.w + "px;");
    lines.push("  height: " + p.h + "px;");
    lines.push("  background-position: -" + p.x + "px -" + p.y + "px;");
    lines.push("}");
  });

  lines.push("");
  lines.push("/* Frame-by-frame playback: change animation-duration to taste. */");
  lines.push("@keyframes " + prefix + "-play {");
  pieces.forEach((p, i) => {
    lines.push("  " + pct(i, n) + "% { background-position: -" + p.x + "px -" + p.y + "px; }");
  });
  const last = pieces[n - 1];
  lines.push("  100% { background-position: -" + last.x + "px -" + last.y + "px; }");
  lines.push("}");
  lines.push("." + prefix + "-anim {");
  lines.push("  width: " + pieces[0].w + "px;");
  lines.push("  height: " + pieces[0].h + "px;");
  lines.push("  animation: " + prefix + "-play " + duration + " " + timing + " " + iterations + ";");
  lines.push("}");
  return lines.join("\n") + "\n";
}

export { slug };
